# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSPsychPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timing_post_trial', models.IntegerField(blank=True, default=1000, null=True)),
                ('on_finish', models.CharField(blank=True, help_text='This should be the name of a function defined for the html.', max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('display_element', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSPsychHTML',
            fields=[
                ('jspsychplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jspsych.JSPsychPlugin')),
                ('url', models.CharField(max_length=255)),
                ('cont_key', models.IntegerField(blank=True, null=True)),
                ('cont_btn', models.CharField(blank=True, max_length=255, null=True)),
                ('check_fn', models.CharField(blank=True, max_length=255, null=True)),
                ('force_refresh', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('jspsych.jspsychplugin',),
        ),
        migrations.CreateModel(
            name='JSPsychSingleStim',
            fields=[
                ('jspsychplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jspsych.JSPsychPlugin')),
                ('stimulus', tinymce.models.HTMLField()),
                ('is_html', models.BooleanField(default=True)),
                ('choices', models.CharField(blank=True, max_length=5)),
                ('prompt', tinymce.models.HTMLField(blank=True, null=True)),
                ('timing_stim', models.IntegerField(default=-1)),
                ('timing_response', models.IntegerField(default=-1)),
                ('response_ends_trial', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('jspsych.jspsychplugin',),
        ),
        migrations.CreateModel(
            name='JSPsychText',
            fields=[
                ('jspsychplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jspsych.JSPsychPlugin')),
                ('text', tinymce.models.HTMLField()),
                ('cont_key', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('jspsych.jspsychplugin',),
        ),
        migrations.AddField(
            model_name='jspsychplugin',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_jspsych.jspsychplugin_set+', to='contenttypes.ContentType'),
        ),
    ]
