# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 23:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSPsychText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timing_post_trial', models.IntegerField(default=1000)),
                ('on_finish', models.CharField(blank=True, help_text='This should be the name of a function defined for the html.', max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('display_element', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('cont_key', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
