# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jspsych', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jspsychtext',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
