# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jspsych', '0002_auto_20160529_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jspsychtext',
            name='display_element',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jspsychtext',
            name='timing_post_trial',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
