# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jspsych', '0003_auto_20160529_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSPsychSingleStim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timing_post_trial', models.IntegerField(blank=True, default=1000, null=True)),
                ('on_finish', models.CharField(blank=True, help_text='This should be the name of a function defined for the html.', max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('display_element', models.CharField(blank=True, max_length=255, null=True)),
                ('stimulus', tinymce.models.HTMLField()),
                ('is_html', models.BooleanField(default=True)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, size=None)),
                ('prompt', tinymce.models.HTMLField(blank=True, null=True)),
                ('timing_stim', models.IntegerField(blank=True, default=-1, null=True)),
                ('timing_response', models.IntegerField(blank=True, default=-1, null=True)),
                ('response_ends_trial', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
