# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jspsych', '0004_jspsychsinglestim'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSPsychHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timing_post_trial', models.IntegerField(blank=True, default=1000, null=True)),
                ('on_finish', models.CharField(blank=True, help_text='This should be the name of a function defined for the html.', max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('display_element', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('cont_key', models.IntegerField(blank=True, null=True)),
                ('cont_btn', models.CharField(blank=True, max_length=255, null=True)),
                ('check_fn', models.CharField(blank=True, max_length=255, null=True)),
                ('force_refresh', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
